%YAML 1.2
---
name:
id:

settings:
  position: [0, 0, 0]
  velocity:
  orientation:
  angular_rates:
  mass:
  agent_id:
  thermal:
  tf:
  file_path:
  max_vel:
  scale: 0.001
  
sensors:
  DummySensor:
    type: "dummy"
    config_path: .\\"config\\sensors\\dummy_sensor.yaml"
    model: ".\\assets\\agents\\basic drone\\simple_drone.obj"
sound:
animation:
model: ".\\assets\\agents\\Generic Quadcopter Drone.obj"