agent: bullet/bullet3/data/Quadrotor/quadrotor.urdf
sensors:
  sensor_1:
    file: sim/sensors/basic_camera.json
    sensor_pos:
      - 0
      - 0
      - -0.05
    sensor_rpy:
      - 0
      - 0
      - 0
  sensor_2:
    file: sim/sensors/basic_ir_camera.json
    sensor_pos:
      - 0
      - 0
      - -0.05
    sensor_rpy:
      - 0
      - 0
      - 0
