Object Labels: labels.json
Layered Surface:
  Mesh: assets/terrain/terrain_type/flat/flat.asc
  Scale:
    - 1
    - 1
    - 1
  Texture: assets/textures/rock.jpg
Surface Mesh:
  - Mesh: assets/terrain/terrain_type/flat/flat.asc
    Rotate Y to Z: false
    YawPitchRoll:
      - 0
      - 0
      - 0
    Position:
      - 0
      - 0
      - 0
    Scale:
      - 1
      - 1
      - 1
  - Mesh: assets/terrain/terrain_features/lowpoly_tree.urdf
    type: tree
    position_type: patch
    patch:
      - 0
      - 0
      - 100
      - 0
      - 100
      - 100
      - 0
      - 100
    density: 0.05
  - Mesh: assets/terrain/terrain_features/cloud.urdf
    type: cloud
    position_type: random
    density: 0.05
    altitude: 60
